-- MySQL Script generated by MySQL Workbench
-- Thu Dec 12 19:41:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sistema` (
  `IdSistema` INT NOT NULL,
  `NombrePrograma` VARCHAR(45) NULL,
  PRIMARY KEY (`IdSistema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `CodigoInsumo` INT NOT NULL,
  `NoEgresoInsumo` INT NULL,
  `NoIngresoInsumo` INT NULL,
  `FechaIngresoInsumo` DATE NULL,
  `FechaEgresoInsumo` DATE NULL,
  `CantidadesInsumos` INT NULL,
  `NoOrden` INT NULL,
  `HorariosdeEntregaInsumo` VARCHAR(45) NULL,
  PRIMARY KEY (`CodigoInsumo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedores` (
  `Nit` INT NOT NULL,
  `RzProveedor` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Telefono2` INT NULL,
  `email` VARCHAR(25) NULL,
  `PersonaContacto` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`Nit`, `PersonaContacto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PerfilesPermisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PerfilesPermisos` (
  `idPerfilesPermisos` INT NOT NULL,
  PRIMARY KEY (`idPerfilesPermisos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Perfiles` (
  `IdCargo` VARCHAR(45) NOT NULL,
  `Cargo` VARCHAR(45) NULL,
  `Funciones` VARCHAR(45) NULL,
  `Perfiles_IdCargo` VARCHAR(45) NOT NULL,
  `PerfilesPermisos_idPerfilesPermisos` INT NOT NULL,
  `PerfilesPermisos_idPerfilesPermisos1` INT NOT NULL,
  `sistema_IdUsuario` INT NOT NULL,
  PRIMARY KEY (`IdCargo`, `Perfiles_IdCargo`),
  INDEX `fk_Perfiles_PerfilesPermisos1_idx` (`PerfilesPermisos_idPerfilesPermisos1` ASC) VISIBLE,
  INDEX `fk_Perfiles_sistema1_idx` (`sistema_IdUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Perfiles_PerfilesPermisos1`
    FOREIGN KEY (`PerfilesPermisos_idPerfilesPermisos1`)
    REFERENCES `mydb`.`PerfilesPermisos` (`idPerfilesPermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Perfiles_sistema1`
    FOREIGN KEY (`sistema_IdUsuario`)
    REFERENCES `mydb`.`sistema` (`IdSistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `Id` INT NOT NULL,
  `ContraseñaUsuario` VARCHAR(45) NULL,
  `TipoDocumento` INT NULL,
  `NoDocumento` INT NULL,
  `Nombre1` VARCHAR(10) NULL,
  `Nombre2` VARCHAR(10) NULL,
  `Apellido1` VARCHAR(10) NULL,
  `Apellido2` VARCHAR(10) NULL,
  `Sexo` VARCHAR(1) NULL,
  `FechaNacimiento` DATE NULL,
  `Cargo` VARCHAR(30) NULL,
  `FechadeIngeso` DATE NULL,
  `Perfiles_IdCargo` VARCHAR(45) NOT NULL,
  `Usuarioscol` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Usuarios_Perfiles1_idx` (`Perfiles_IdCargo` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Perfiles1`
    FOREIGN KEY (`Perfiles_IdCargo`)
    REFERENCES `mydb`.`Perfiles` (`IdCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facturacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facturacion` (
  `NumFactura` INT NOT NULL,
  `TotalVenta` INT NULL,
  `FechaIngreso` DATE NULL,
  `Nit` INT NULL,
  `CodigoInsumo` INT NULL,
  `pedido_CodigoInsumo` INT NOT NULL,
  `proveedores_Nit` INT NOT NULL,
  `Usuarios_Id` INT NOT NULL,
  PRIMARY KEY (`NumFactura`),
  INDEX `fk_facturacion_pedido1_idx` (`pedido_CodigoInsumo` ASC) VISIBLE,
  INDEX `fk_facturacion_proveedores1_idx` (`proveedores_Nit` ASC) VISIBLE,
  INDEX `fk_facturacion_Usuarios1_idx` (`Usuarios_Id` ASC) VISIBLE,
  CONSTRAINT `fk_facturacion_pedido1`
    FOREIGN KEY (`pedido_CodigoInsumo`)
    REFERENCES `mydb`.`pedido` (`CodigoInsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturacion_proveedores1`
    FOREIGN KEY (`proveedores_Nit`)
    REFERENCES `mydb`.`proveedores` (`Nit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturacion_Usuarios1`
    FOREIGN KEY (`Usuarios_Id`)
    REFERENCES `mydb`.`Usuarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Insumos` (
  `Codigo` INT NOT NULL,
  `DescripcionCodigo` VARCHAR(100) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detalle Factura` (
  `Codigo` INT NOT NULL,
  `PesoInsumo` INT NULL,
  `FechaIngreso` DATE NULL,
  `FechaVencimientoInsumo` INT NULL,
  `RzProveedor` VARCHAR(45) NULL,
  `MarcaInsumo` VARCHAR(45) NULL,
  `Valor` INT NULL,
  `fechaEgreso` DATE NULL,
  `facturacion_NumFactura` INT NOT NULL,
  `Insumos_Codigo` INT NOT NULL,
  INDEX `fk_insumos_facturacion1_idx` (`facturacion_NumFactura` ASC) VISIBLE,
  INDEX `fk_Detalle Factura_Insumos1_idx` (`Insumos_Codigo` ASC) VISIBLE,
  PRIMARY KEY (`Codigo`),
  CONSTRAINT `fk_insumos_facturacion1`
    FOREIGN KEY (`facturacion_NumFactura`)
    REFERENCES `mydb`.`facturacion` (`NumFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle Factura_Insumos1`
    FOREIGN KEY (`Insumos_Codigo`)
    REFERENCES `mydb`.`Insumos` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Permisos` (
  `idUsuarios` INT NOT NULL,
  `IdPermisos` VARCHAR(45) NULL,
  `PerfilesPermisos_idPerfilesPermisos` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  INDEX `fk_Permisos_PerfilesPermisos1_idx` (`PerfilesPermisos_idPerfilesPermisos` ASC) VISIBLE,
  CONSTRAINT `fk_Permisos_PerfilesPermisos1`
    FOREIGN KEY (`PerfilesPermisos_idPerfilesPermisos`)
    REFERENCES `mydb`.`PerfilesPermisos` (`idPerfilesPermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reportes` (
  `idReportes` INT NOT NULL,
  `sistema_IdSistema` INT NOT NULL,
  `NombreReporte` VARCHAR(300) NULL,
  `ConsultaReporte` VARCHAR(200) NULL,
  `IdProgama` VARCHAR(45) NULL,
  PRIMARY KEY (`idReportes`),
  INDEX `fk_Reportes_sistema1_idx` (`sistema_IdSistema` ASC) VISIBLE,
  CONSTRAINT `fk_Reportes_sistema1`
    FOREIGN KEY (`sistema_IdSistema`)
    REFERENCES `mydb`.`sistema` (`IdSistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
